### ISSUE TITLE
二维码登不上去，报错。

### ISSUE THREAD

**Issue by X-233** [zhayujie/CowAgent#1106]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

KeyError: 'wxsid'

### 问题描述 😯

报错

### 终端日志 📒

```log
[ERROR][2023-05-16 20:42:40][app.py:52] - App startup failed!
[ERROR][2023-05-16 20:42:40][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/home/AI/ChatGPT_2/chatgpt-on-wechat/app.py", line 50, in run
    channel.startup()
  File "/home/AI/ChatGPT_2/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 116, in startup
    itchat.auto_login(
  File "/home/AI/ChatGPT_2/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/home/AI/ChatGPT_2/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/home/AI/ChatGPT_2/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/home/AI/ChatGPT_2/chatgpt-on-wechat/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
```

**Comment by Fate0x01** [comment]
itchat 新账号是登不了的

**Comment by lanvent** [comment]
是否绑定银行卡实名认证

**Comment by Songsci1024** [comment]
绑定了银行卡并实名就可以了

**Comment by Fate0x01** [comment]
> 绑定了银行卡并实名就可以了

我看了一些资料，这些资料说明了新账号即使绑定银行卡并实名，也无法使用itchat的。

**Comment by dongweiq** [comment]
已经实名认证了，上午还能用，晚上就不能用了，很奇怪，相同的报错。
`
Please press confirm on your phone.
[ERROR][2023-05-29 22:48:36][app.py:52] - App startup failed!
[ERROR][2023-05-29 22:48:36][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/Users/honghe/PycharmProjects/chatgpt-on-wechat/app.py", line 50, in run
    channel.startup()
  File "/Users/honghe/PycharmProjects/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 115, in startup
    itchat.auto_login(
  File "/Users/honghe/PycharmProjects/chatgpt-on-wechat/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/honghe/PycharmProjects/chatgpt-on-wechat/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/Users/honghe/PycharmProjects/chatgpt-on-wechat/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/Users/honghe/PycharmProjects/chatgpt-on-wechat/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
`

**Comment by JohnLizt** [comment]
同样的问题，已实名，挂了一天自动登出后就上不去了，有人有头绪吗

**Comment by ruanjunmin** [comment]
我也是，这个错误：
Please press confirm on your phone.
<PIL.PngImagePlugin.PngImageFile image mode=1 size=450x450 at 0x7FE295C872E0>
[ERROR][2024-12-12 09:16:36][wechat_channel.py:138] - 'wxsid'
Traceback (most recent call last):
  File "/app/channel/wechat/wechat_channel.py", line 124, in startup
    itchat.auto_login(
  File "/app/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/app/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/app/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/app/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
