### ISSUE TITLE
扫码登录后报错

### ISSUE THREAD

**Issue by 1150549059** [zhayujie/CowAgent#1243]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

安装教程进行安装部署，扫码后，出现报错

### 问题描述 😯

安装教程进行安装部署，扫码后，出现报错

### 终端日志 📒

```log
Please press confirm on your phone.
[ERROR][2023-06-12 07:40:25][app.py:52] - App startup failed!
[ERROR][2023-06-12 07:40:25][app.py:53] - 'wxsid'
Traceback (most recent call last):
  File "/data/chatgpt-on-wechat-master/app.py", line 50, in run
    channel.startup()
  File "/data/chatgpt-on-wechat-master/channel/wechat/wechat_channel.py", line 115, in startup
    itchat.auto_login(
  File "/data/chatgpt-on-wechat-master/lib/itchat/components/register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/data/chatgpt-on-wechat-master/lib/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/data/chatgpt-on-wechat-master/lib/itchat/components/login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "/data/chatgpt-on-wechat-master/lib/itchat/components/login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
^C[1]+  Done                    nohup python3 app.py
```

**Comment by yanxdyxd** [comment]
微信号需要实名认证

**Comment by 1150549059** [comment]
> 微信号需要实名认证

4.5 的目前支持吗

**Comment by zhayujie** [comment]
> > 微信号需要实名认证
> 
> 4.5 的目前支持吗

你是说gpt-4吗， 你有api的权限的话 是支持的

**Comment by ChrisGray0626** [comment]
感谢我也有这个问题。请问该部分可以加入文档吗，或者在报错时提示一下？感恩～

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
