### ISSUE TITLE
目前出了新模型了，项目是否已经支持啦？需要更改config么？

### ISSUE THREAD

**Issue by dwd923** [zhayujie/CowAgent#1247]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by lanvent** [comment]
修改配置中的model就能使用

**Comment by dwd923** [comment]
> 修改配置中的model就能使用，如果要使用16k model，`conversation_max_tokens` 需要配合修改大一点

gpt-3.5-turbo-16k-0613

**Comment by lanvent** [comment]
- gpt3.5 
"gpt-3.5-turbo-0301", "gpt-3.5-turbo-0613", "gpt-35-turbo", "gpt-3.5-turbo-16k", "gpt-3.5-turbo-16k-0613"
- gpt4 
"gpt-4-0314", "gpt-4-0613", "gpt-4-32k", "gpt-4-32k-0613"

**Comment by GesiIvy128** [comment]
我将model改为"gpt-3.5-turbo-0613"提问后却报错：
﻿[INFO][2023-06-17 10:55:28][chat_gpt_bot.py:49] - [CHATGPT] query=你在吗
﻿[WARNING][2023-06-17 10:55:30][chat_gpt_session.py:77] - num_tokens_from_messages() is not implemented for model gpt-3.5-turbo-0613. Returning num tokens assuming gpt-3.5-turbo-0301.
﻿[WARNING][2023-06-17 10:55:31][chat_gpt_session.py:77] - num_tokens_from_messages() is not implemented for model gpt-3.5-turbo-0613. Returning num tokens assuming gpt-3.5-turbo-0301.
﻿[ERROR][2023-06-17 10:55:31][chat_channel.py:270] - Worker return exception: can only concatenate list (not "str") to list
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
﻿result = self.fn(*self.args, **self.kwargs)
﻿File "/app/channel/chat_channel.py", line 150, in _handle
﻿reply = self._decorate_reply(context, reply)
﻿File "/app/channel/chat_channel.py", line 228, in _decorate_reply
﻿reply_text = conf().get("single_chat_reply_prefix", "") + reply_text
﻿TypeError: can only concatenate list (not "str") to list

我是用railway部署的

**Comment by chenjin0827** [comment]
> 
一样的问题,解决了吗

**Comment by shxch** [comment]
相同的问题，我觉得应该把单聊prefix去掉，应该没人会在单聊的时候还加个前缀吧

[INFO][2023-07-12 18:17:23][chat_gpt_bot.py:49] - [CHATGPT] query=hi
﻿[ERROR][2023-07-12 18:17:26][chat_channel.py:270] - Worker return exception: can only concatenate list (not "str") to list
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
﻿result = self.fn(*self.args, **self.kwargs)
﻿File "/app/channel/chat_channel.py", line 150, in _handle
﻿reply = self._decorate_reply(context, reply)
﻿File "/app/channel/chat_channel.py", line 228, in _decorate_reply
﻿reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "")
﻿TypeError: can only concatenate list (not "str") to list

**Comment by GesiIvy128** [comment]
我觉得从逻辑角度 不该去掉单聊的prefix, 因为你的小号可能加了其他人，你总不会希望随便一个什么人问你小号问题，你的小号都化身bot吧

> 相同的问题，我觉得应该把单聊prefix去掉，应该没人会在单聊的时候还加个前缀吧
> 
> [INFO][2023-07-12 18:17:23][chat_gpt_bot.py:49] - [CHATGPT] query=hi ﻿[ERROR][2023-07-12 18:17:26][chat_channel.py:270] - Worker return exception: can only concatenate list (not "str") to list ﻿Traceback (most recent call last): ﻿File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run ﻿result = self.fn(*self.args, **self.kwargs) ﻿File "/app/channel/chat_channel.py", line 150, in _handle ﻿reply = self._decorate_reply(context, reply) ﻿File "/app/channel/chat_channel.py", line 228, in _decorate_reply ﻿reply_text = conf().get("single_chat_reply_prefix", "") + reply_text + conf().get("single_chat_reply_suffix", "") ﻿TypeError: can only concatenate list (not "str") to list

**Comment by shxch** [comment]
有道理诶，是我考虑不周了

**Comment by hellosmarter** [comment]
@lanvent  修改配置中的model修改成了gpt-4-0613，运行是提示下面这个告警，这个应该不影响使用gpt4模型吧，只是说这个token计算不准是吧？
另外最新的代码有没有把这个警告fix掉了，因为我用的还是比较之前旧一点的代码，谢谢
[WARNING][2023-07-31 00:12:48][chat_gpt_session.py:76] - num_tokens_from_messages() is not implemented for model gpt-4-0613. Returning num tokens assuming gpt-3.5-turbo-0301.

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
