### ISSUE TITLE
docker 版启动不了下面是报错信息

### ISSUE THREAD

**Issue by nick814** [zhayujie/CowAgent#1293]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

直接  运行docker compose up -d  就报错了

### 问题描述 😯

我看帮助里  访问微信网站和访问google都没问题
[root@localhost docker]# wget login.weixin.qq.com
--2023-07-05 10:47:17--  http://login.weixin.qq.com/
Resolving login.weixin.qq.com (login.weixin.qq.com)... 43.129.255.96, 240e:e1:a802:1::1c
Connecting to login.weixin.qq.com (login.weixin.qq.com)|43.129.255.96|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://login.weixin.qq.com/ [following]
--2023-07-05 10:47:18--  https://login.weixin.qq.com/
Connecting to login.weixin.qq.com (login.weixin.qq.com)|43.129.255.96|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87921 (86K) [text/html]
Saving to: ‘index.html’

100%[=================================================================>] 87,921      --.-K/s   in 0.07s   

2023-07-05 10:47:18 (1.29 MB/s) - ‘index.html’ saved [87921/87921]

[root@localhost docker]# wget google.com
--2023-07-05 10:48:01--  http://google.com/
Resolving google.com (google.com)... 142.250.66.142, 2404:6800:4005:81d::200e
Connecting to google.com (google.com)|142.250.66.142|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2023-07-05 10:48:01--  http://www.google.com/
Resolving www.google.com (www.google.com)... 142.251.220.36, 2404:6800:4005:80d::2004
Connecting to www.google.com (www.google.com)|142.251.220.36|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=http://www.google.com.hk/&ust=1688525311700466&usg=AOvVaw3527FznE52G4weQsusfqvF [following]
--2023-07-05 10:48:01--  http://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=http://www.google.com.hk/&ust=1688525311700466&usg=AOvVaw3527FznE52G4weQsusfqvF
Resolving www.google.com.hk (www.google.com.hk)... 142.251.220.3, 2404:6800:4005:80c::2003
Connecting to www.google.com.hk (www.google.com.hk)|142.251.220.3|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.google.com.hk/ [following]
--2023-07-05 10:48:01--  http://www.google.com.hk/
Reusing existing connection to www.google.com.hk:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

    [ <=>                                                              ] 17,827      --.-K/s   in 0.03s   

2023-07-05 10:48:01 (548 KB/s) - ‘index.html.1’ saved [17827]

### 终端日志 📒

```log
Traceback (most recent call last):
  File "/app/lib/itchat/utils.py", line 134, in test_connect
    r = requests.get(config.BASE_URL)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f85e9553430>: Failed to establish a new connection: [Errno -3] Try again'))

```

**Comment by nick814** [comment]
我的机器是直接用了到香港的专线

**Comment by 6vision** [comment]
梯子开规则模式，不要开全局

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
