### ISSUE TITLE
运行WeChat后，时常有报错，偶尔影响微信使用，会掉线。

### ISSUE THREAD

**Issue by fattank** [zhayujie/CowAgent#1424]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

Traceback (most recent call last):
  File "/home/tank/.local/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/tank/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/tank/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tank/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/tank/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/tank/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tank/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tank/chatgpt/chatgpt-on-wechat-master0721/lib/itchat/components/login.py", line 301, in maintain_loop
    msgList, contactList = self.get_msg()
  File "/home/tank/chatgpt/chatgpt-on-wechat-master0721/lib/itchat/components/login.py", line 390, in get_msg
    r = self.s.post(url, data=json.dumps(data),

### 问题描述 😯

我查过chatgpt的反馈，有说是网络问题和证书问题。但是没有解决办法，所以请教。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by zhayujie** [comment]
访问wx的网络问题， 海外的服务器？

如果用代理的话注意开规则模式

**Comment by chendong0** [comment]
是使用aws的lightstail的win10系统和Linux中的docker部署，均存在28小时后自动掉线。如何能长期的保持程序的正常运行呢？谢谢。

**Comment by ViperGash** [comment]
> 访问wx的网络问题， 海外的服务器？
> 
> 如果用代理的话注意开规则模式

我部署在railway的。应该没有代理问题吧

**Comment by lei195827** [comment]
> 是使用aws的lightstail的win10系统和Linux中的docker部署，均存在28小时后自动掉线。如何能长期的保持程序的正常运行呢？谢谢。

使用自动回复插件能一定程度上延长在线时间，但是还是无法避免掉线

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
