### ISSUE TITLE
账号有chat4的权限，把key放进去改了模型提示does not exist or you do not have access to it

### ISSUE THREAD

**Issue by xionghaizhi** [zhayujie/CowAgent#1591]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

使用gpt-4 模型，提示没有授权，页面chat4 可以使用

### 问题描述 😯

使用gpt-4 模型，提示没有授权，页面chat4 可以使用

### 终端日志 📒

```log
[INFO][2023-12-12 09:52:59][bridge.py:45] - create bot chatGPT for chat
[INFO][2023-12-12 09:52:59][chat_gpt_bot.py:49] - [CHATGPT] query=123
[ERROR][2023-12-12 09:53:03][chat_gpt_bot.py:155] - [CHATGPT] Exception: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
Traceback (most recent call last):
  File "/home/weixin/newWeixin/chatgpt-on-wechat-master/bot/chatgpt/chat_gpt_bot.py", line 123, in reply_text
    response = openai.ChatCompletion.create(api_key=api_key, messages=session.messages, **args)
  File "/usr/local/python3/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/python3/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/python3/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/python3/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
[INFO][2023-12-12 09:53:03][wechat_channel.py:194] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我现在有点累了，等会再来吧), receiver=@325bbcf23d6c090e6897dbe4a225dd6821f8465c584034f65a3462d4c5ef0e77

```

**Comment by zhayujie** [comment]
在这看有没有API的权限 https://platform.openai.com/account/limits

**Comment by rolsy** [comment]
> 在这看有没有API的权限 https://platform.openai.com/account/limits
![1715450856002](https://github.com/zhayujie/chatgpt-on-wechat/assets/49657099/c9c00ad9-3013-481f-af79-d4b9def24d68)
gpt-4的权限怎么整啊，我这个gpt-4-0613没法用吧

**Comment by zhayujie** [comment]
Thanks for reporting this! This issue has had no activity for over a year and predates our major rewrite, so we're closing it during a backlog cleanup.

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) has been upgraded to 2.0** — an open-source super AI assistant & agent harness. It plans tasks, runs tools and skills, and autonomously grows with memory and a local knowledge base. Multi-model, multi-channel, lightweight, extensible, one-line install.

If your need still applies to the new version, we'd love to hear it — feel free to open a fresh issue. ❤️

---

感谢反馈！此 issue 一年多没有活动，且属于项目大版本重构之前的时期，我们在清理历史 backlog 时将其关闭。

🚀 **[CowAgent](https://github.com/zhayujie/CowAgent) 已升级到 2.0**，升级为开源的超级 AI 助手 & Agent Harness 框架。能规划任务、调用工具与技能，并通过记忆和本地知识库自主成长。多模型、多渠道，轻量、可扩展，一行命令安装。

如果你的需求在新版本上依然适用，欢迎新建一个 issue 告诉我们 ❤️
